apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk044-sk-agentry-fe
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk044-sk-agentry-fe
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 01b1c22af1ef272b35b0a6761ae3f1d3
      labels:
        app: sk044-sk-agentry-fe
    spec:
      serviceAccountName: default
      containers:
      - name: sk-agentry-fe
        image: amdp-registry.skala-ai.com/skala25a/sk044-my-app:2.0.0-3-f80e04cca763
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
        env:
          - name: LOGGING_LEVEL
            value: DEBUG
          - name: USER_NAME
            value: sk044
          - name: NAMESPACE
            value: skala-practice
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        envFrom:
          - secretRef:
              name: sk-agentry-fe-secrets