apiVersion: v1
kind: Secret
metadata:
  name: sk-agentry-fe-secrets
  namespace: skala-practice
type: Opaque
stringData:
  VITE_API_BASE_URL: "https://sk044.skala25a.project.skala-ai.com/api"
  VITE_MODE: "production"
  # 필요 시 여기에 추가하세요